### ISSUE TITLE
Found that the page layout is incorrect after opening the page

### ISSUE THREAD

**Issue by renyu666** [cloudy-sfu/QuestionGo#2]
![image](https://user-images.githubusercontent.com/64844086/81071139-d7280c80-8f16-11ea-852f-cac80a04dbce.png)

**Comment by cloudy-sfu** [comment]
It seems that your browser can't load the CSS file.
Try:
1. Clear your browse history.
2. It seems that your browser can't recognize XHTML pages, and it's preferrable for you to comment the following code:
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
3. Don't use old browsers like IE or Microsoft Edge based on the IE core.
